config/routes.rb
Rails.application.routes.draw do
  get 'trump', to: 'politician#trump'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/politician_controller.rb
class PoliticianController < ApplicationController
  before_action yt_configure, only: [:trump]

  def trump
    # @youtube = Yt::Playlist.new(id: 'PLRJNAhZxtqH-fd1x12yYa-hKuxoZ8Npnz').playlist_items
  end

  def yt_configure
    # Yt.configure do |config|
    #   config.api_key = 'AIzaSyCc-NMroCyISYoj6VUNPmO3qvctu2jrCc0'
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/politician_helper.rb
module PoliticianHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealityChecker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <div class="content">
      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </div>
    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>About page</h1>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <h1>Contact Us</h1>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(https://images.unsplash.com/photo-1586369610007-2b1cc66dadde?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80); background-position: center top;">
  <div class="container">
    <h1>Check political claims against <strong>statistical reality</strong>!</h1>
    <p>Because it's 2020, yet something like this is still necessary.</p>
    <a class="btn btn-primary" href="#">How it works</a>
  </div>
</div>
<div class="container">
  <div class="about-section">
    <h3 style="text-align: center; margin-bottom: 20px;">Why Build This?</h3>
    <div class="about-contents">
      <p>Something strange has been happening over the past few years, where people of opposing political viewpoints can't seem to agree on what events are transpiring in basic reality. Flip between Fox News and MSNBC and you'd think you were looking through a portal into the multiverse, describing two totally different realities.</p>
      <p>To me it seems that this is part of a "fight for survival" by antiquated economic entities (major media news outlets) thrashing about in an attempt to survive in an environment they weren't built for, combined with the thought bubbles created by social media that stoke divisiveness and tribal mentality, diminishing rational discourse in the process.</p>
      <p>I'm of the mindset that if we strip away the nonsense and look at the core facts, we can get a clearer picture. What did X politician say about corona virus? When did they say it? What information did we have access to at that point in time? From there people can draw their own conclusions about the quality of the decisions made.</p>
    </div>
  </div>
</div>

app/views/politician/trump.html.erb
<div class="container">
  <h1>Politician#trump</h1>
  <p>Find me in app/views/politician/trump.html.erb</p>
  <div class="tweet-box" style="width: 400px;">
    <a class="twitter-timeline" href="https://twitter.com/realDonaldTrump?ref_src=twsrc%5Etfw">Tweets by realDonaldTrump</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div>
    <h6 style="margin-bottom: 0; width: 100%; text-align: center;">Developer links:</h6>
    <div class="footer-left">
      <a href="https://brandon-olin-dev-portfolio.herokuapp.com/"><i class="fas fa-globe"></i></a>
      <a href="https://github.com/brandon-olin"><i class="fab fa-github"></i></a>
      <a href="https://www.linkedin.com/in/brandon-olin/"><i class="fab fa-linkedin"></i></a>
      <a href="https://twitter.com/BrandonOlin"><i class="fab fa-twitter"></i></a>
    </div>
  </div>
  <div class="footer-copyright">
    Website made by Brandon Olin
  </div>
  <div class="footer-right">
    <%= link_to "About", about_path %>
    <%= link_to "Contact", contact_path %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Reality Checker", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "About", about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Politician
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Donald Trump", trump_path, class: 'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>